global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.3.229:8081']
        labels:
          application: 'spring-app'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.3.229:9090']